### ISSUE TITLE
Layout of Clones

### ISSUE THREAD

**Issue by christopherreay** [ndebeiss/svg3d#3]
Nico,

Could you add a layout for clone3d which conforms to the Golden Ration

1.61803398874989
1
0.618033988749897

where 1.6 is the x axis, 1 is y and 0.6 is z?
Im doing it in my code, and I was going to abstract it away somewhere. Seems the best place to put it would be svg3d... Maybe not.. Worth doing if its a ten minute job imo

**Comment by ndebeiss** [comment]
Hi

You can specify a custom geographic distribution of clones, as it is done in svg3d/examples/js/Box_clip_art.js :

```
	$("#layer1").each(function( index, elm ) {
		elm.svg3dCloneGeographicDistribution = function(cloneIndex, clone3drow, clone3dlayer, clone3dx, clone3dy, clone3dz) {
			var layer = Math.floor( cloneIndex / clone3dlayer );
			var row = Math.floor( ( cloneIndex % clone3dlayer ) / clone3drow);
			var z = Math.floor( ( ( cloneIndex % clone3dlayer ) % clone3drow ) );
			return {incx: clone3dx * row,
					incy: clone3dy * layer,
					incz: clone3dz * z};
		};
	});
```

By default, it just adds the increments specified in svg3d.clone3d.x, svg3d.clone3d.y, svg3d.clone3d.z to the coordinates of the original element :

```
svg3d: {
      clone3d: {
        row: 10,
        x: 50,
        layer: 100,
        y: 50,
        z: 50,
        nb: 300
      }
    }
```

Give me the code you did for your distribution, I will make an example with it.

**Comment by christopherreay** [comment]
so we are using clone3d with fixed x, y, z the point is that the natural
order crafted by the cloning process is the sane as the occlusion ordering.
there is no need to do any threed analysis on the clones to know what order
to add the faces to the scene.

that is until the camera moves around.

what you appear to be saying is that the camera position is not taken into
account when calculating the order of the faces, which is why the 4 z faces
are eQual distance

is there a tool in svg3d that allows the user to move the camera? if not
should I just make calls to translate3d.. I suppose so

**Comment by ndebeiss** [comment]
It is another discussion :-) , you are talking about sorting the parallel faces of a cube ?

Indeed the camera position can just be modified by the position of the vanishing point, svg3d.xInfinite and svg3d.yInfinite. So the camera position stays in front of the screen, it juste looks to another point.

And indeed you can add a 3d translation.

But :

"what you appear to be saying is that the camera position is not taken into
account when calculating the order of the faces, which is why the 4 z faces
are eQual distance"

should be wrong, the vanishing point should be taken as the center of the camera, do you have an example where it does not work ?
Can you make translations of the cubes from left to right and up and down around the vanishing point in order to see what is happening ?
with :
```
svg3d: {
			translate3d : {x: 400, y: 300, z: 0},
```
