### ISSUE TITLE
Questions and thanks

### ISSUE THREAD

**Issue by thednp** [ndebeiss/svg3d#5]
Hello and thanks for your wonderful code. I'm reading and loving it!

I have 3 questions:
* if I manage to understand how this works and how to adapt to my need, do you mind if I add you directly to my special thanks page?
* the current working draft SVG 1.1 does not support 3d transform functions on *SVGPathElement*, not yet as of 2020, does this means your code basically compensates the Z axis transformation by calculating the 2D coordinates to MIMIC the 3D presentation, do I understand correctly?
* I haven't finished reading the code yet, so I'm not sure: can this code be adapted to work with a given 3d matrix?

Thank you and GOD bless man, you made my day!

**Comment by ndebeiss** [comment]
Hello

First, thank you for your interest and that evaluation of my code.

> if I manage to understand how this works and how to adapt to my need, do you mind if I add you directly to my special thanks page?

You can of course adapt it and everything else, and it would be a honor to be on your thanks page :-).

> the current working draft SVG 1.1 does not support 3d transform functions on SVGPathElement, not yet as of 2020, does this means your code basically compensates the Z axis transformation by calculating the 2D coordinates to MIMIC the 3D presentation, do I understand correctly?

Yes that is what the code does, it has a 3D scene of objects in memory, and it projects it on the screen in order to mimic the 3D.

That code was made a long time ago, when svg did not have much interoperability with CSS. Then the team of thisequalsthat asked me some improvements, so I added some code.

> I haven't finished reading the code yet, so I'm not sure: can this code be adapted to work with a given 3d matrix?

At the time I coded it, there was no easy access to 3D rendering code, like the excellent three.js library. I had no knowledge of quaternions, 4*4 matrix, etc... My projection code is not correct when camera moves behind the screen and lots of other situations.

I would be very happy if the library could be recoded with all the real algorithms of 3D rendering, keeping the principles of 3D declaration of the svg like I wanted it. I may be able to help you.

There is also code in three.js in order to render a scene in SVG. I do not know the state of it, i do not think it can support everything.

Best regards!

**Comment by ndebeiss** [comment]
Ok I read the other question you asked on the svg spec repo.

You can apply any matrix on the "node" DOM element with the following code :

```javascript
var shape = svg3d.shapeFactory(node);
shape.transform([3dmatrix]);
```

the matrix is an array of 12 numbers, as in the example :

```javascript
svg3d.setTranslationMatrix = function(x, y, z) {
   return [
	1, 0, 0, x,
        0, 1, 0, y,
        0, 0, 1, z
        ];
    }
```

See the example :

https://github.com/ndebeiss/svg3d/blob/e620e04db3401af57ab848c600966ef710bf9252/examples/rg1024_metal_barrel.svg
with the associated javascript : 
https://github.com/ndebeiss/svg3d/blob/e620e04db3401af57ab848c600966ef710bf9252/examples/js/rg1024_metal_barrel.js

with the code :

```javascript
	var shapeAxex = svg3d.shapeFactory(document.getElementById("axex"));
	shapeAxex.transform([svg3d.setTranslationMatrix(0, 0, 0)]);
```

**Comment by thednp** [comment]
Wow man, take it easy! Thank you for the time you took to reply :D

I made a cool [little tool](https://thednp.github.io/svg-path-commander/) to manipulate SVG path data, something of a hybrid of Raphael.js (for path command operations), SvgPath (the best svg path string parser I know), some Paper.js (for determining the shape draw direction), and the entire codebase is modernized ES6+. Heck I don't even use SVGMatrix API, I use DOMMatrix to calculate path command transformation. 

My additions to the bunch is the ability to reverse path commands, transform path commands, calculate total path length (not possible in Node.js, currently working with a Raphael.js tool, but looking to finish my [own implementation](https://stackoverflow.com/questions/63859009/svgpathelement-calculate-arc-length) very soon)

I'm looking for ways to enable more creativity for my users in creating [SVG Morph](https://thednp.github.io/kute.js/svgMorph.html) animations, I was thinking of a way to transform path commands to 3D, so I came here :)

I only know I can apply a "tuple" multiplication, or "multiply a vector by a matrix" but I don't know what I need from your code, not yet, so far [this part](https://github.com/ndebeiss/svg3d/blob/master/svg3d/svg3d.js#L100-L308) seems the right part, just I'm not sure where to begin, a little help might be of use.

Maybe we can also optimize your code a little bit, how about a 60fps animation with 3D SVG? I've never seen one :)

**Comment by ndebeiss** [comment]
Ok, I see, that looks good. You may add features in order to apply filters, they are powerful but not easy to write.

The code you see parses the d attribute, and rewrites it into the svg. There is extra complexity because if threeD attribute is present, I allow the path to be declared with 3 coordinates on each point.

The projection of the 3d point on the screen is done there :
https://github.com/ndebeiss/svg3d/blob/master/svg3d/svg3d.js#L1014-1018

but is not good, it would be better to use code like that :
https://github.com/mrdoob/three.js/blob/ff48de58e216bc72abb4085a080c5acb66f2f584/examples/js/renderers/Projector.js#L844

meaning you multiply the vector by a projection matrix created by a PerspectiveCamera :
https://github.com/mrdoob/three.js/blob/cd41804aa436bb2cfd79797c04985f75c4c63e63/src/cameras/PerspectiveCamera.js#L182

The matrix4 creates its perspective :
https://github.com/mrdoob/three.js/blob/1983589c07c6ae833a23763562496e5197b48516/src/math/Matrix4.js#L772

I do not know about all the other matrix which are calculated...

> Maybe we can also optimize your code a little bit, how about a 60fps animation with 3D SVG? I've never seen one :)

The setInterval is fixed, I think it can be reduced to have a 60 fps animation. Not sure it takes a lot of CPU.

**Comment by thednp** [comment]
That resource you're linking from Three.js is awesome, so I put some thinking before replying to you, so in y mind this is too far from our scope and objective. Please allow me to explain:

* first, we don't need a Vector4 + Vector3 + Vector2 or and entire Silvester Math library to compute what we already have at hand: DOMMatrix, gets you the computed matrix, instantly, we only polyfill it in Node.js, but only for a quick transformation, while Three.js is a doom escape ready library for WebGL, the best JS library probably ever;
* second, we only need to adjust some code to work with this type of pathArray `[['M',0,0],['L',0,0]]` which to my eyes, your code seems to be close to
* lastly and possibly most importantly, the ARC path command is pretty trixxy, if you change its radius it's a hell of a problem, a problem I managed to solve by converting the arc commands to CUBIC bezier, the problem arises when you're looking to calculate the arc length for other operations like `getTotalLength` for which I'm also working on a polyfill for Node.js, but overall I believe you're on my side in this development.

Cheers man.

**Comment by thednp** [comment]
I'm testing your script and checking the values computed. I'm trying to understand how it works.
Ready for more questions?

* Why is the computed matrix a 12 numbers array? Isn't a `matrix3d` supposed to work with 16 values?
* If it's 12, then you're removing the perspective matrix, or what exactly is missing?
* For some reasons, the script completely disregards the `viewBox` attribute and always compute values way out of the viewport, is there something I'm missing?
* Why sometimes I get NaN and undefined in the path data? Probably you should skip cases where the matrix `isIdentity`? (This is something I had to fix in my code as well)

This is what I do with your script added to my [demo page](https://thednp.github.io/svg-path-commander/):

```js

var shape = svg3d.shapeFactory(document.getElementByTagName('path')[0]);

// and apply the matrix array you want by calling :
var matrixArray = [];
matrixArray[0] = svg3d.setAnglesRotationMatrix(0,0,45);
shape.transform(matrixArray);

console.log(shape,matrixArray)
```

**Comment by thednp** [comment]
I have it to work a little bit, just I can't seem to figure out this `matrixArray`, what would be the equivalent of that into a DOMMatrix instance with 16 values please?

**Comment by thednp** [comment]
Yea, I have it working but a hell to configure, probably need some rest. I implemented the `transform` method from CSSMatrix polyfill:

```js
transform = function(t /* tuple */ ){
 	let m = this,
 		x = m.m11 * t.x + m.m12 * t.y + m.m13 * t.z + m.m14 * t.w,
 		y = m.m21 * t.x + m.m22 * t.y + m.m23 * t.z + m.m24 * t.w,
 		z = m.m31 * t.x + m.m32 * t.y + m.m33 * t.z + m.m34 * t.w,
 		w = m.m41 * t.x + m.m42 * t.y + m.m43 * t.z + m.m44 * t.w;

 	t.x = x / w;
 	t.y = y / w;
 	t.z = z / w;

 	return t;
 }	
```
Cheeeeeeeeeeeeeerrrrrrrrrrrssssssssssssssss !!

**Comment by ndebeiss** [comment]
Hello

I do not have much time to answer, the 4th line of a 4*4 3d matrix is full of 0 and a 1 at the last column, see
https://stackoverflow.com/questions/29079685/how-does-4x4-matrix-work-in-3d-graphic

I will look at the demo, glad you made it work!

**Comment by thednp** [comment]
I have some projections going on but because the SVG coordinates system which is different from the standard HTMLElement box model, this projection isn't working with the DOMMatrix properly, I think would have to implement your matrix constructor.

With the identity matrix3d I'm getting the path projected to an 90 degrees angle on X axis and I can't see it, or sometimes it's going out of the parent SVG viewport.

So perhaps this isn't going the way we want.

**Comment by thednp** [comment]
I have the good news at hand: I'm rolling this feature in the next version, crazy?

I found [the script](https://stackoverflow.com/questions/23792505/predicted-rendering-of-css-3d-transformed-pixel) that does the job, exactly what I wanted.

**Comment by thednp** [comment]
@ndebeiss aside from having it to work perfect with all other path commands, I can't find a solution for `A` and [your code here](https://github.com/ndebeiss/svg3d/blob/master/svg3d/svg3d.js#L198) isn't very helpful. This probably has to do with your comment

> //TODO modify x_axis_rotation with rotation on y (-rotY % (2*Math.PI)) * 360 / (2*Math.PI)

**Comment by thednp** [comment]
I'm going to put the `A` on hold, meanwhile...

https://thednp.github.io/svg-path-commander/

**Comment by thednp** [comment]
Hi @ndebeiss how you doin?

I remembered about this topic and wanted to check on you, are you still developing stuff or active in any way on Github?

I recently found some code to work with Arc path commands and the only thing left to solve is the 3D transformation (the point at length and segment length are done on my local machine), so I came to the only one in the world that might have what I hope to be a solution.

I'm looking at your [half_pipe_3d_declared](http://debeissat.nicolas.free.fr/blog/?cat=14) example and your code, I don't understand what you're doing with the xRadius, yRadius, xAxisRotation parameters. Also in the demo, the arcs seem to move up and down once a cycle, is that intentional?

In brief, this is what I understand from your code so far:
* you're parsing and rebuilding the path strings on the fly in the same function body
* you're using mostly Absolute values to compute X2, Y2, both before and after computation
* you seem to leave some parameters unchanged

Other [sources](https://github.com/phetsims/kite/blob/master/js/segments/EllipticalArc.ts) seem to do something different, if I understand correctly they create an ellipse, apply transformation and convert back to Arc segment, which is something I might have to try eventually.

So how does your example work? Can you make a simple arc transformation demonstration? That would be so awesome :)

Cheers

**Comment by ndebeiss** [comment]
Hello

I am doing well thank you, and you ?
I am not actively developing on Github, but I still work in software development.

I read the code again, and I do not think that works. It only transforms rx and ry so if one of those values become very small, it will create a big arc, and it is not intentional at all.

The source you give looks very good !

Maybe try adding the code :

```javascript
    const reflected = matrix.getDeterminant() < 0;

    // reverse the 'clockwiseness' if our transform includes a reflection
    // TODO: check reflections. swapping angle signs should fix clockwiseness
    const anticlockwise = reflected ? !this._anticlockwise : this._anticlockwise;
    const startAngle = reflected ? -this._startAngle : this._startAngle;
    let endAngle = reflected ? -this._endAngle : this._endAngle;

    if ( Math.abs( this._endAngle - this._startAngle ) === Math.PI * 2 ) {
      endAngle = anticlockwise ? startAngle - Math.PI * 2 : startAngle + Math.PI * 2;
    }
```

regards
